# Generated by Django 5.1.2 on 2024-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
