# Generated by Django 5.1.2 on 2024-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_email_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='reason',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('tuition', 'Tuition Inquiry'), ('technical', 'Technical Support'), ('other', 'Other')], max_length=20),
        ),
    ]
