# Generated by Django 5.1.2 on 2024-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_email_verified'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, related_name='purchasers', to='shop.product'),
        ),
    ]
