services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8080
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
