# Generated by Django 4.2.10 on 2024-12-18 19:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import stream.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=stream.storage.PublicMediaStorage(), upload_to='news/images/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('none', 'No Resource'), ('pdf', 'PDF Document'), ('worksheet', 'Worksheet'), ('guide', 'Guide'), ('other', 'Other Resource')], default='none', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=stream.storage.PublicMediaStorage(), upload_to='news/thumbnails/')),
                ('resource', models.FileField(blank=True, null=True, storage=stream.storage.SecureFileStorage(), upload_to='news/resources/')),
                ('resource_title', models.CharField(blank=True, help_text='Name of the downloadable resource', max_length=200)),
                ('ad_type', models.CharField(choices=[('none', 'No Advertisement'), ('adsense', 'Google AdSense'), ('banner', 'Banner Image')], default='none', max_length=10)),
                ('ad_code', models.TextField(blank=True)),
                ('ad_image', models.ImageField(blank=True, null=True, storage=stream.storage.PublicMediaStorage(), upload_to='news/ads/')),
                ('ad_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title (60 characters max)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Description (160 characters max)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category')),
            ],
            options={
                'ordering': ['-publish_date', '-created'],
            },
        ),
    ]
