# Generated by Django 5.1.2 on 2024-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_hero_content_hero_cta_link_hero_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='New Videos Available!', max_length=200)),
                ('action_text', models.CharField(default="See what's new", max_length=100)),
                ('action_link', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('badge_text', models.CharField(default='New', max_length=50)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
            },
        ),
    ]
