# Generated by Django 5.1.2 on 2024-12-06 09:53

import cloudinary.models
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Take A Look At My Latest Courses', max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('show_courses_section', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='View All Courses', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Courses Section',
                'verbose_name_plural': 'Courses Section',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('subtitle', models.CharField(help_text="e.g., 'Helping Students achieve Grade 9'", max_length=200)),
                ('description', models.TextField(help_text='Introduction paragraph about yourself')),
                ('qualifications', models.TextField(help_text='List of qualifications - stored as plain text')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Me Section',
                'verbose_name_plural': 'About Me Section',
            },
        ),
        migrations.CreateModel(
            name='AboutTuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tuition Lessons', max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('booking_title', models.CharField(default='Book Your Session', max_length=200)),
                ('booking_description', django_ckeditor_5.fields.CKEditor5Field()),
                ('booking_button_text', models.CharField(default='Book HERE!', max_length=50)),
                ('booking_button_url', models.CharField(default='/booking-form/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tuition Information',
                'verbose_name_plural': 'Tuition Information',
            },
        ),
    ]
