# Generated by Django 5.1.2 on 2024-12-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_create_missing_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('book', 'Book'), ('pencil', 'Pencil'), ('star', 'Star'), ('certificate', 'Certificate'), ('users', 'Users'), ('lightbulb', 'Lightbulb')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tuition Feature',
                'verbose_name_plural': 'Tuition Features',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='historicalpage',
            name='template',
            field=models.CharField(choices=[('home', 'Homepage'), ('about', 'About Page'), ('tuition', 'Tuition Page')], max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('home', 'Homepage'), ('about', 'About Page'), ('tuition', 'Tuition Page')], max_length=20),
        ),
    ]
