# Generated by Django 5.1.2 on 2024-12-10 14:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_tuitionfeature_alter_historicalpage_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='second_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='second_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
