# Generated by Django 5.1.2 on 2024-12-10 15:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_historicalpage_second_content_page_second_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('second_title', models.CharField(max_length=200)),
                ('second_description', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Me Columns',
                'verbose_name_plural': 'About Me Columns',
            },
        ),
        migrations.DeleteModel(
            name='AboutTuition',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='qualifications',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Introduction paragraph about yourself'),
        ),
    ]
