# Generated by Django 5.1.2 on 2024-12-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_aboutmecolumns_delete_abouttuition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='subtitle',
        ),
    ]
