# Generated by Django 5.1.2 on 2024-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_aboutme_image_remove_aboutme_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
