# Generated by Django 5.1.2 on 2024-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=130, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email', 'Email required')], default='email', max_length=5)),
                ('status', models.CharField(choices=[('publish', 'Published'), ('soon', 'Coming Soon'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
