# Generated by Django 5.1.2 on 2024-10-19 16:56

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
