# Generated by Django 5.1.2 on 2024-12-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_stripe_id_order_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_details', to='shop.order')),
            ],
            options={
                'verbose_name_plural': 'Guest Details',
            },
        ),
    ]
